// Mocks generated by Mockito 5.4.6 from annotations
// in tuto_riverpod_clean_arch/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tuto_riverpod_clean_arch/auth/data/client/auth_client.dart'
    as _i10;
import 'package:tuto_riverpod_clean_arch/auth/data/datasources/auth_fake_data_source.dart'
    as _i9;
import 'package:tuto_riverpod_clean_arch/auth/data/datasources/auth_remote_data_source.dart'
    as _i7;
import 'package:tuto_riverpod_clean_arch/auth/data/models/auth_request.dart'
    as _i8;
import 'package:tuto_riverpod_clean_arch/auth/data/models/user_model.dart'
    as _i2;
import 'package:tuto_riverpod_clean_arch/auth/domain/entities/user.dart' as _i5;
import 'package:tuto_riverpod_clean_arch/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserState> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i5.UserState>.value(
              _i6.dummyValue<_i5.UserState>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.UserState>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i7.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserState> login(_i8.AuthRequest? authRequest) =>
      (super.noSuchMethod(
            Invocation.method(#login, [authRequest]),
            returnValue: _i4.Future<_i5.UserState>.value(
              _i6.dummyValue<_i5.UserState>(
                this,
                Invocation.method(#login, [authRequest]),
              ),
            ),
          )
          as _i4.Future<_i5.UserState>);
}

/// A class which mocks [AuthFakeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthFakeDataSource extends _i1.Mock
    implements _i9.AuthFakeDataSource {
  MockAuthFakeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.UserState> login(_i8.AuthRequest? authRequest) =>
      (super.noSuchMethod(
            Invocation.method(#login, [authRequest]),
            returnValue: _i4.Future<_i5.UserState>.value(
              _i6.dummyValue<_i5.UserState>(
                this,
                Invocation.method(#login, [authRequest]),
              ),
            ),
          )
          as _i4.Future<_i5.UserState>);
}

/// A class which mocks [AuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthClient extends _i1.Mock implements _i10.AuthClient {
  MockAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> login(_i8.AuthRequest? body) =>
      (super.noSuchMethod(
            Invocation.method(#login, [body]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#login, [body])),
            ),
          )
          as _i4.Future<_i2.UserModel>);
}
